boat: {

    sail: {
        pressure_point_height: 2.48, # [m]
        height:                 6.2, # [m]
        area:                   6.4, # [m^2]
        length:                   1, # [m]
        stretching:           0.961
    },

    rudder: {
        stretching: 2.326923076923077, 
        area:                    0.13  # [m^2]
    },

    keel: {
        height:      0.55, # [m]
        length:         2, # [m]
        stretching: 0.605
    },

    length:             4, # [m]
    mass:             350, # [kg]
    height_bouyancy: 0.15, # [m]
    lateral_area:     2.5, # [m^2]
    waterline_area:   1.6, # [m^2]

    # cog: center of gravity
    distance_cog_sail_pressure_point:  0.43, # [m]
    distance_cog_keel_pressure_point:  0.24, # [m]
    distance_cog_rudder:               1.24, # [m]
    distance_mast_sail_pressure_point: 0.68, # [m]

    # moi: moment of inertia
    geometrical_moi_x: 0.256,
    geometrical_moi_y: 25.6,
    moi_x: 25.6,
    moi_y: 1600,
    moi_z: 1066,

    roll_damping:      0.25,
    pitch_damping:     0.25,
    damping_z:          0.2,
    yaw_timeconstant:     5,
    along_damping:       15,
    transverse_damping:   5,
    hull_speed:         2.5
}

environment: {
    water_viscosity: 0.0000001, # [Pa * s]
    air_viscosity:   0.0000171, # [Pa * s]
    water_density:        1000, # [kg/m^3]
    air_density:           1.3, # [kg/m^3]
    gravity:              9.81  # [m/s^2]
}

simulator: {

    stepper: {
        # time controls
        stepsize:          0.1, # [s]  how far into the future to simulate
        clockrate:          10, # [Hz] how often to simulate
    },

    # Initial state of simulation
    initial: {
        vel_x: 0, # [m/s]
        vel_y: 0, # [m/s]
        vel_z: 0, # [m/s]

        yaw:   0,
        pitch: 0,
        roll:  0,

        roll_rate:  0,
        pitch_rate: 0,
        yaw_rate:   0,

        latitude:     18.306292, # [deg]
        longitude:   -64.951150, # [deg]

        wind_strength:   5.0,  # [m/s] 5.0 m/s ~= 4-5 bft
        wind_direction:  45.0, # [deg] wind from north-north-east

        wave_direction: 220.0,  # [deg] unused, keep for the future
        wave_length:      2.0,  # [m]   unused
        wave_amplitude:   0.0,  # [m]   unused

        sail_angle:   1,      # [rad]
        rudder_angle: 1,      # [rad]
    }
}
